import { FullVehicleReport } from '../types/vehicle';

export const MOCK_REPORTS: Record<string, FullVehicleReport> = {
  // Veículo 100% Aprovado
  'BRA2E19': {
    id: 'REP-98101',
    consultedAt: new Date().toISOString(),
    basicInfo: {
      plate: 'BRA2E19',
      brand: 'HONDA',
      model: 'CIVIC TOURING 1.5 TURBO',
      version: 'Touring Turbo CVT',
      yearFabrication: 2021,
      yearModel: 2022,
      color: 'Branco Pérola',
      fuel: 'Gasolina',
      city: 'São Paulo',
      state: 'SP',
      chassisMasked: '93HFC1680NZ******',
      renavamMasked: '0129845****',
      engineMasked: 'L15BA198****',
      fipeValue: 148500,
      fipeCode: '014093-7',
    },
    cadastral: {
      chassis: '93HFC1680NZ849201',
      engine: 'L15BA198304921',
      renavam: '01298456102',
      origin: 'Nacional',
      powerHp: '173 cv',
      cylinderCapacity: '1.498 cm³',
      vehicleType: 'Sedã',
      segment: 'Sedã Médio',
      passengers: 5,
      fipeValue: 148500,
      fipeCode: '014093-7',
      fipeHistory: [
        { month: 'Mar/25', value: 154000 },
        { month: 'Jun/25', value: 152000 },
        { month: 'Set/25', value: 150000 },
        { month: 'Dez/25', value: 149200 },
        { month: 'Mar/26', value: 148500 },
      ],
    },
    financial: {
      hasDebts: false,
      totalDebtsAmount: 0,
      ipvaStatus: 'OK',
      licensingStatus: 'OK',
      debtsList: [],
      gravame: {
        hasFinancialRestriction: false,
        status: 'Quitado',
      },
    },
    risks: {
      overallRiskLevel: 'safe',
      riskScore: 96,
      riskSummary: 'Excelente procedência! Sem apontamento de leilão, sinistro ou débitos. Histórico de revisões e odômetro consistentes.',
      theftRecord: { isStolenOrTheftAlert: false, status: 'Sem Alerta de Furto/Roubo' },
      judicialRestrictions: { hasRestriction: false, type: 'Sem Restrição Judicial' },
      auction: { hasAuction: false, auctionScoreRisk: 0 },
      accident: { hasAccident: false, severity: 'Sem Registros' },
      recall: { hasPendingRecall: false },
      tamperingAlert: { hasMileageTamperingSuspicion: false },
    },
    ownersMileage: {
      totalOwnersCount: 1,
      currentOwnerType: 'Pessoa Física',
      usageProfile: 'Uso Particular Moderado',
      estimatedCurrentMileage: 38400,
      ownerHistory: [
        { ownerNumber: 1, ownerType: 'Pessoa Física', state: 'SP', periodStart: '03/2022', periodEnd: 'Atual', durationMonths: 48 },
      ],
      mileageHistory: [
        { date: '03/2022', mileage: 12, source: 'Revisão Concessionária' },
        { date: '04/2024', mileage: 19400, source: 'Revisão Concessionária' },
        { date: '01/2026', mileage: 38400, source: 'Laudo Cautelar' },
      ],
    },
  },

  // Veículo de Referência (Jeep Compass com Score 87, Gravame Ativo e sem débitos/leilão)
  'ABC1D23': {
    id: 'REP-77342',
    consultedAt: new Date().toISOString(),
    basicInfo: {
      plate: 'ABC1D23',
      brand: 'Jeep',
      model: 'Compass',
      version: 'Limited 2.0 Flex',
      yearFabrication: 2020,
      yearModel: 2021,
      color: 'Cinza',
      fuel: 'Flex',
      city: 'Curitiba',
      state: 'PR',
      chassisMasked: '9886FB830MY******',
      renavamMasked: '0118392****',
      engineMasked: 'Tigershark20****',
      fipeValue: 119800,
      fipeCode: '017042-9',
    },
    cadastral: {
      chassis: '9886FB830MY491028',
      engine: 'Tigershark20938192',
      renavam: '01183927491',
      origin: 'Nacional',
      powerHp: '166 cv',
      cylinderCapacity: '1.995 cm³',
      vehicleType: 'Utilitário esportivo',
      segment: 'SUV Médio',
      passengers: 5,
      fipeValue: 119800,
      fipeCode: '017042-9',
      fipeHistory: [
        { month: 'Mar/25', value: 128000 },
        { month: 'Jun/25', value: 125000 },
        { month: 'Set/25', value: 122000 },
        { month: 'Dez/25', value: 120500 },
        { month: 'Mar/26', value: 119800 },
      ],
    },
    financial: {
      hasDebts: false,
      totalDebtsAmount: 0,
      ipvaStatus: 'OK',
      licensingStatus: 'OK',
      debtsList: [],
      gravame: {
        hasFinancialRestriction: true,
        financialInstitution: 'BANCO SANTANDER S.A.',
        inclusionDate: '14/09/2023',
        status: 'Alienado Fiduciariamente',
      },
    },
    risks: {
      overallRiskLevel: 'safe',
      riskScore: 87,
      riskSummary: 'O histórico consultado não apresentou ocorrências relevantes para a compra deste veículo.',
      theftRecord: { isStolenOrTheftAlert: false, status: 'Sem Alerta de Furto/Roubo' },
      judicialRestrictions: { hasRestriction: false, type: 'Sem Restrição Judicial' },
      auction: {
        hasAuction: false,
        auctionScoreRisk: 0,
      },
      accident: { hasAccident: false, severity: 'Sem Registros' },
      recall: { hasPendingRecall: false },
      tamperingAlert: { hasMileageTamperingSuspicion: false },
    },
    ownersMileage: {
      totalOwnersCount: 2,
      currentOwnerType: 'Pessoa Física',
      usageProfile: 'Uso Particular Moderado',
      estimatedCurrentMileage: 52400,
      ownerHistory: [
        { ownerNumber: 1, ownerType: 'Pessoa Física', state: 'SP', periodStart: '10/2020', periodEnd: '09/2023', durationMonths: 35 },
        { ownerNumber: 2, ownerType: 'Pessoa Física', state: 'PR', periodStart: '09/2023', periodEnd: 'Atual', durationMonths: 30 },
      ],
      mileageHistory: [
        { date: '10/2020', mileage: 0, source: 'Revisão Concessionária' },
        { date: '05/2022', mileage: 22400, source: 'Revisão Concessionária' },
        { date: '09/2023', mileage: 38100, source: 'Laudo Cautelar' },
        { date: '02/2026', mileage: 52400, source: 'Detran' },
      ],
    },
  },

  // Veículo com Alto Risco Crítico
  'XYZ9876': {
    id: 'REP-11094',
    consultedAt: new Date().toISOString(),
    basicInfo: {
      plate: 'XYZ9876',
      brand: 'VOLKSWAGEN',
      model: 'GOL 1.6 MSI TOTALFLEX',
      version: '1.6 MSI Manual',
      yearFabrication: 2018,
      yearModel: 2019,
      color: 'Prata',
      fuel: 'Flex',
      city: 'Belo Horizonte',
      state: 'MG',
      chassisMasked: '9BWAB45U9KT******',
      renavamMasked: '0104819****',
      engineMasked: 'EA211MSI09****',
      fipeValue: 47900,
      fipeCode: '005472-0',
    },
    cadastral: {
      chassis: '9BWAB45U9KT719302',
      engine: 'EA211MSI0941920',
      renavam: '01048194821',
      origin: 'Nacional',
      powerHp: '104 cv',
      cylinderCapacity: '1.598 cm³',
      vehicleType: 'Hatch',
      segment: 'Hatch Compacto',
      passengers: 5,
      fipeValue: 47900,
      fipeCode: '005472-0',
      fipeHistory: [
        { month: 'Mar/25', value: 51200 },
        { month: 'Jun/25', value: 49800 },
        { month: 'Set/25', value: 48900 },
        { month: 'Dez/25', value: 48200 },
        { month: 'Mar/26', value: 47900 },
      ],
    },
    financial: {
      hasDebts: true,
      totalDebtsAmount: 5115.20,
      ipvaStatus: 'Atrasado',
      licensingStatus: 'Atrasado',
      debtsList: [
        { id: '1', type: 'IPVA', year: 2024, description: 'IPVA 2024 Inscrito em Dívida Ativa', organ: 'SEF-MG', dueDate: '2024-04-15', amount: 2180.50, status: 'Inscrito em Dívida Ativa' },
        { id: '2', type: 'Multa', description: 'Dirigir sob influência de álcool (Art. 165 CTB)', organ: 'BHTRANS', dueDate: '2025-02-14', amount: 2934.70, status: 'Pendente' },
      ],
      gravame: {
        hasFinancialRestriction: true,
        financialInstitution: 'BANCO BV FINANCEIRA',
        inclusionDate: '21/11/2021',
        status: 'Alienado Fiduciariamente',
      },
    },
    risks: {
      overallRiskLevel: 'danger',
      riskScore: 18,
      riskSummary: 'ALTO RISCO! Veículo com bloqueio judicial RENAJUD, suspeita de adulteração de odômetro (-65.000 km), dívida ativa e gravame ativo.',
      theftRecord: { isStolenOrTheftAlert: false, status: 'Sem Alerta de Furto/Roubo' },
      judicialRestrictions: {
        hasRestriction: true,
        type: 'Renajud - Transferência',
        courtName: '2ª Vara Cível de BH/MG - Proc. 5019***-82.2024',
      },
      auction: {
        hasAuction: true,
        auctioneer: 'Copart',
        comitente: 'Financeira BV',
        lotNumber: 'Lote 8821',
        category: 'Recuperado de Financiamento',
        damageLevel: 'Sem Danos',
        auctionScoreRisk: 45,
      },
      accident: { hasAccident: false, severity: 'Sem Registros' },
      recall: { hasPendingRecall: true, campaignName: 'Recall Airbag Takata', urgency: 'Alta' },
      tamperingAlert: {
        hasMileageTamperingSuspicion: true,
        notes: 'ADULTERAÇÃO: 142.000 km em 2023 reduzido para 78.000 km em 2025.',
      },
    },
    ownersMileage: {
      totalOwnersCount: 5,
      currentOwnerType: 'Pessoa Física',
      usageProfile: 'Uso Misto',
      estimatedCurrentMileage: 156000,
      ownerHistory: [
        { ownerNumber: 1, ownerType: 'Pessoa Jurídica (Locadora)', state: 'SP', periodStart: '08/2018', periodEnd: '03/2020', durationMonths: 19 },
        { ownerNumber: 2, ownerType: 'Pessoa Física', state: 'MG', periodStart: '03/2020', periodEnd: 'Atual', durationMonths: 72 },
      ],
      mileageHistory: [
        { date: '08/2018', mileage: 0, source: 'Revisão Concessionária' },
        { date: '04/2023', mileage: 142000, source: 'Detran' },
        { date: '11/2024', mileage: 78000, source: 'Anúncio Web', isSuspect: true },
      ],
    },
  },
};

/**
 * Gera relatório simplificado e limpo para qualquer placa informada
 */
export function generateDynamicReportForPlate(plate: string): FullVehicleReport {
  const clean = plate.toUpperCase().replace(/[^A-Z0-9]/g, '');
  if (MOCK_REPORTS[clean]) return MOCK_REPORTS[clean];

  return {
    ...MOCK_REPORTS['BRA2E19'],
    id: `REP-${clean.slice(0, 4)}`,
    basicInfo: {
      ...MOCK_REPORTS['BRA2E19'].basicInfo,
      plate: clean,
    },
  };
}
